### ISSUE TITLE
Login redirection doesn't work on firefox android

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/3Bot_connect#130] opened 2020-09-08 07:05 UTC
I'm unable to login to a 3bot connect enabled website when I use Firefox for android.
It seems the redirection to the login page after I click accept from the app never happens. Which leave me on the 3bot login page forever.

![Screenshot_20200908-090502.jpg](https://user-images.githubusercontent.com/303164/92443898-6fc6e580-f1b2-11ea-8d32-8d0273fac4cc.jpg)

**Comment by ken-de-moor** [comment] 2020-09-08 13:25
Duplicate of https://github.com/threefoldtech/3Bot_connect/issues/66

**Closed by ken-de-moor** 2020-09-08 13:25 UTC
